FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /router
COPY requirements.txt /router/requirements.txt
RUN pip install --no-cache-dir -r /router/requirements.txt

COPY router /router/router
EXPOSE 8080

CMD ["uvicorn", "router.main:app", "--host", "0.0.0.0", "--port", "8080"]

